### ISSUE TITLE
Invariantin massan kaavat

### ISSUE THREAD

**Issue by katilp** [cms-opendata-education/cms-jupyter-materials-finnish#10]
Lisää esim, notebookiin https://github.com/cms-opendata-education/cms-jupyter-materials-finnish/blob/master/Opetusmateriaalit/AvoinDataHiukkasfysiikassa/3_Data-analyysi/01_LaskeInvarianttiMassa.ipynb maininta siitä, että cosh... kaava on approksimaatio, joka toimiii silloin kun E  &#8811; m

**Comment by peitsaveteli** [comment]
Tämä korjattu ja sekalainen läjä rikkinäisiä linkkejä siistitty (mm. Demot-kansion ohjeistus ja Aalto Juniori -puolen linkitys).
